### ISSUE TITLE
How to install Symbolic-math-HaTeX by stack?

### ISSUE THREAD

**Issue by vincent-hui** [leftaroundabout/Symbolic-math-HaTeX#1]
When I install Symbolic-math-HaTeX by ```stack install TeX-my-math```
I got the follow error messages
```
Error: While constructing the build plan, the following exceptions were encountered:

In the dependencies for TeX-my-math-0.201.1.1:
    decimal-literals needed, but the stack configuration has no specified version  (latest matching version is 0.1.0.0)
    dumb-cas must match >=0.1.1.1 && <0.2, but the stack configuration has no specified version  (latest matching version is 0.1.2.0)
needed since TeX-my-math is a build target.

Some different approaches to resolving this:

  * Consider trying 'stack solver', which uses the cabal-install solver to attempt to find some working build configuration. This can be
    convenient when dealing with many complicated constraint errors, but results may be unpredictable.

  * Recommended action: try adding the following to your extra-deps in /home/vincent/.stack/global-project/stack.yaml:

decimal-literals-0.1.0.0@sha256:bbbc02afd83bb261543ae7f81b14a016cfa0170d3972fc57993d6ab9d0340c93
dumb-cas-0.1.2.0@sha256:a64c86c086cfc7e2a5d348d05e8f842d1165959dc405fc27a05688226abdba40

Plan construction failed.
```

**Comment by leftaroundabout** [comment]
Thanks for the interest! Yeah, my packages' Stack support is always a bit behind. In particular with TeX-my-math, there's a couple of things we still haven't quite finished over at HaTeX, that I already use here... should get that done.

See the https://github.com/leftaroundabout/Symbolic-math-HaTeX/tree/stack-build/HaTeX-3.19.0.0-prime branch that I made for a working, albeit hacked `stack.yaml` configuration.

I should include this properly and add Travis testing too...

**Comment by leftaroundabout** [comment]
Actually HaTeX itself is fine, there's just some dependency issues left.

https://github.com/ekmett/wl-pprint-extras/pull/18
https://github.com/Daniel-Diaz/HaTeX/issues/126

But with `allow-newer: true` in your `.stack/config.yaml`, it should work from [the branch I linked](https://github.com/leftaroundabout/Symbolic-math-HaTeX/tree/stack-build/HaTeX-3.19.0.0-prime)

**Comment by vincent-hui** [comment]
Thank you very much! I can build Symbolic-math-HaTeX by stack.
Would you mind giving me an example how to generate tex files from hs files containing math equations?

**Comment by leftaroundabout** [comment]
https://github.com/leftaroundabout/Symbolic-math-HaTeX/blob/master/example/Simple.hs

**Comment by vincent-hui** [comment]
Thank you very much. The example works for me !!
Do you think stack-build/HaTeX-3.19.0.0-prime can be merged into master?

**Comment by leftaroundabout** [comment]
146894b94c595358e65bead4a1f5f27445f4b8c3
