### ISSUE TITLE
use correct utf8 setminus

### ISSUE THREAD

**Issue by jorsn** [leftaroundabout/Symbolic-math-HaTeX#4]
Setminus is currently mapped to `⧵`, which is U+29F5 REVERSE SOLIDUS OPERATOR.
As utf8 has an official SET MINUS, which is `∖` (U+2216), i tried this one first, so I'd propose to use it instead or add it and deprecate U+29F5 (like `-\-`).

For reference, see e.g. <https://en.wikipedia.org/wiki/Mathematical_operators_and_symbols_in_Unicode>.

**Comment by leftaroundabout** [comment]
e0fec7f
